### ISSUE TITLE
Schema is not up-to-date 

### ISSUE THREAD

**Issue by pakrym** [Azure/perks#78]
With update to 
`'@autorest/modelerfour' (4.2.75->4.2.75)` & `@autorest\core\dist' (3.0.6162)` we are getting `tabDelimited` style in http parameter.

```
        protocol: !<!Protocols> 
          http: !<!HttpParameter> 
            in: query
            style: tabDelimited
```

It's not represented in schema:

https://github.com/Azure/perks/blob/master/codemodel/.resources/all-in-one/json/code-model.json#L2016

**Comment by fearthecowboy** [comment]
fixed 

https://github.com/Azure/perks/blob/master/codemodel/.resources/all-in-one/yaml/code-model.yaml#L1849
