### ISSUE TITLE
RequestBody parameter definition is lost when converting swagger 2.0 to 3.0

### ISSUE THREAD

**Issue by leniatgh** [Azure/perks#83]
For request body parameters defined in a common place only for reference, it's lost when converting to 3.0.
https://github.com/Azure/perks/blob/master/oai2-to-oai3/main.ts#L204
``` 
visitParameterDefinitions(parameters: Iterable<Node>) {
    for (const { key, value, pointer, childIterator } of parameters) {
      if (value.in !== 'formData' && value.in !== 'body' && value.type !== 'file') {
```

**Comment by leniatgh** [comment]
Hi @fearthecowboy, is there any update?

**Comment by timotheeguerin** [comment]
@leni-msft Could you reclarify what is the problem here? Do you have a repro in particular?

Would this happen to be the same issue that was fixed here https://github.com/Azure/perks/pull/131

**Comment by leniatgh** [comment]
@timotheeguerin please see repro here: https://github.com/Azure/autorest.azureresourceschema/issues/42#issuecomment-641793510

**Comment by timotheeguerin** [comment]
@leni-msft I believe this is the same issue that I fixed. Could you check it is still happening https://github.com/Azure/autorest/issues/3546#issuecomment-743475769

**Comment by leniatgh** [comment]
@timotheeguerin Great! The issue is gone. Thanks very much!
